Gemfile:
  optional:
    ':development':
      - gem: 'puppet-lint-absolute_classname-check'
      - gem: 'puppet-lint-classes_and_types_beginning_with_digits-check'
      - gem: 'puppet-lint-leading_zero-check'
      - gem: 'puppet-lint-param-docs'
      - gem: 'puppet-lint-resource_reference_syntax'
      - gem: 'puppet-lint-trailing_comma-check'
      - gem: 'puppet-lint-trailing_newline-check'
      - gem: 'puppet-lint-unquoted_string-check'
      - gem: 'puppet-lint-variable_contains_upcase'
      - gem: 'puppet-lint-version_comparison-check'
    ':system_tests':
      - gem: 'beaker'
      - gem: 'beaker-rspec'
      - gem: 'beaker-puppet_install_helper'

Rakefile:
  linter_fail_on_warnings: true

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
  minimum_code_coverage_percentage: 95
